schemaVersion: "2.0.0"

commandTests:
  - name: "XDebug Version Check"
    command: "php-fpm"
    args: ["-v"]
    expectedOutput:
      - "(?m)^\\s+with Xdebug"
  - name: "Xdebug Module Loaded"
    command: "php-fpm"
    args: ["-m"]
    expectedOutput:
      - "(?m)^xdebug"
  - name: "Xdebug Extension Configured"
    command: "php-fpm"
    args: ["-i"]
    expectedOutput:
      - "(?m)^Support Xdebug on"
      - "(?m)^xdebug\\.idekey => PHPSTORM => PHPSTORM"
      - "(?m)^xdebug\\.remote_enable => \\(setting renamed in Xdebug 3\\) => \\(setting renamed in Xdebug 3\\)"

fileExistenceTests:
  - name: "Xdebug Configuration File Exists"
    path: "/etc/php.d/15-xdebug.ini"
    shouldExist: true

fileContentTests:
  - name: "Xdebug Configuration"
    path: "/etc/php.d/15-xdebug.ini"
    expectedContents:
      - "(?m)^xdebug\\.remote_addr_header=\"HTTP_X_DEBUG_HOST\""
    excludedContents:
      - "(?m)^xdebug\\.client_discovery_header=\"HTTP_X_DEBUG_HOST,HTTP_X_FORWARDED_FOR,REMOTE_ADDR\""