schemaVersion: "2.0.0"

commandTests:
  - name: "PHP-FPM Exists"
    command: "which"
    args: ["php-fpm"]
    expectedOutput: ["/usr/sbin/php-fpm"]
  - name: "SourceGuardian Module Loaded"
    command: "php-fpm"
    args: ["-m"]
    expectedOutput:
      - "(?m)SourceGuardian"
  - name: "SourceGuardian Info Check"
    command: "php-fpm"
    args: ["-i"]
    expectedOutput:
      - "/etc/php\\.d/15-sourceguardian.ini"
      - "(?m)^SourceGuardian Loader Support => enabled"
      - "(?m)^sourceguardian\\.enable_debug => 0 => 0"

fileExistenceTests:
  - name: "SourceGuardian Config Exists"
    path: "/etc/php.d/15-sourceguardian.ini"
    shouldExist: true