schemaVersion: "2.0.0"

commandTests:
  - name: "SPX Module Loaded"
    command: "php-fpm"
    args: ["-m"]
    expectedOutput:
      - "(?m)^SPX"
  - name: "SPX Configuration Check"
    command: "php-fpm"
    args: ["-i"]
    expectedOutput:
      - "(?m)^spx\\.debug => 1 => 1"
      - "(?m)^spx\\.http_key => warden => warden"

fileExistenceTests:
  - name: "SPX Config Exists"
    path: "/etc/php.d/30-spx.ini"
    shouldExist: true