schemaVersion: "2.0.0"

commandTests:
  - name: "XDebug Version Check (Generic)"
    command: "php-fpm"
    args: ["-v"]
    expectedOutput:
      - "(?m)^\\s+with Xdebug v3\\."
  - name: "Xdebug Module Loaded"
    command: "php-fpm"
    args: ["-m"]
    expectedOutput:
      - "(?m)^xdebug"
  - name: "Xdebug Configuration"
    command: "php-fpm"
    args: ["-i"]
    expectedOutput:
      - "(?m)^Support Xdebug on"
      - "(?m)^xdebug\\.idekey => PHPSTORM => PHPSTORM"

fileExistenceTests:
  - name: "Xdebug Configuration File Exists"
    path: "/etc/php.d/15-xdebug.ini"
    shouldExist: true