commandTests:
  - name: "XDebug Version Check"
    command: "php-fpm"
    args: ["-v"]
    expectedOutput:
      - "(?m)^\\+with Xdebug v3\\.[3456789]\\."
    excludedOutput:
      - "(?m)^\\+with Xdebug v3\\.[012]\\." # Xdebug 3.2 is for xdebug3 variants only

fileContentTest:
  - name: "Xdebug 3"
    path: "/etc/php.d/15-xdebug.ini"
    expectedContents:
      - "(?m)^xdebug\\.client_discovery_header=\"HTTP_X_DEBUG_HOST\""
    excludedContents:
      - "(?m)^xdebug\\.client_discovery_header=\"HTTP_X_DEBUG_HOST,HTTP_X_FORWARDED_FOR,REMOTE_ADDR\""