schemaVersion: "2.0.0"

commandTests:
  - name: "ionCube Module Loaded"
    command: "php-fpm"
    args: ["-m"]
    expectedOutput:
      - "(?m)^the ionCube PHP Loader"
  - name: "ionCube Configuration Check"
    command: "php-fpm"
    args: ["-i"]
    expectedOutput:
      - "/etc/php\\.d/01-ioncube-loader.ini"
      - "(?m)^For Loader updates visit www\\.ioncube\\.com/loaders\\.php"
      - "(?m)^ioncube\\.loader\\.encoded_paths => no value => no value"

fileExistenceTests:
  - name: "IonCube Config Exists"
    path: "/etc/php.d/01-ioncube-loader.ini"
    shouldExist: true