schemaVersion: "2.0.0"

commandTests:
  - name: "PHP Module Check"
    command: "php"
    args: ["-m"]
    expectedOutput:
      - "(?m)^the ionCube PHP Loader"
  - name: "PHP Config Check"
    command: "php"
    args: ["-i"]
    expectedOutput:
      - "/etc/php\\.d/01-ioncube-loader.ini"
      - "(?m)^For Loader updates visit www\\.ioncube\\.com/loaders\\.php"
      - "(?m)^ioncube\\.loader\\.encoded_paths => no value => no value"

fileExistenceTests:
  - name: "IonCube Config"
    path: "/etc/php.d/01-ioncube-loader.ini"
    shouldExist: true