name: Base PHP Images
on:
  push:
    branches:
      - main
    paths:
      - php/**
      - .github/workflows/base-php.yml
jobs:
  build:
    name: Build PHP Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          PRE_AUTH: 1
          IMAGE_NAME: ghcr.io/wardenenv/centos-php
          VERSION_LIST: 7.4 8.0 8.1 8.2
          VARIANT_LIST: cli cli-loaders fpm fpm-loaders
          PUSH_FLAG: 1
        run: bash php/scripts/build.sh