name: Warden PHP Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - php-fpm/**
      - scripts/build.sh
      - .github/workflows/warden-php.yml
jobs:
