name: Warden PHP Images
on:
  push:
    branches:
      - main
    paths:
      - php-fpm/**
      - scripts/build.sh
      - .github/workflows/warden-php.yml
jobs:
  php-fpm:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.4", "8.0", "8.1", "8.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          BUILD_GROUP: php-fpm
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/wardenenv
          PHP_SOURCE_IMAGE: ghcr.io/wardenenv/centos-php
          PUSH_FLAG: 1
        run: bash scripts/build.sh "${BUILD_GROUP}"

  magento1:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }} (magento1)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.4", "8.0", "8.1", "8.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          BUILD_GROUP: php-fpm/magento1
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/wardenenv
          PHP_SOURCE_IMAGE: ghcr.io/wardenenv/centos-php
          PUSH_FLAG: 1
        run: bash scripts/build.sh "${BUILD_GROUP}"

  magento2:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }} (magento2)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.4", "8.0", "8.1", "8.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          BUILD_GROUP: php-fpm/magento2
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/wardenenv
          PHP_SOURCE_IMAGE: ghcr.io/wardenenv/centos-php
          PUSH_FLAG: 1
        run: bash scripts/build.sh "${BUILD_GROUP}"